# Site settings
title: "Corentin Hatte (Helyo Sphere)"
title_short: "Corentin Hatte"
company_name: "Helyo Sphere"
email: "prospect@corentin-hatte.eu"
phone: "+33665424497"
siret: "83124174000016"
description: >-
  Développeur Web freelance à Rennes (Bretagne), expert Opquast Maîtrise de la qualité Web
baseurl: ""
url: "https://www.corentin-hatte.eu"
twitter_username: HelyoSphere
language: "fr"
timezone: "Europe/Paris"
encoding: UTF-8
permalink: /articles/:categories/:title:output_ext
excerpt_separator: <!-- /excerpt -->
paginate: 6
paginate_path: "/articles/page:num/"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed

jekyll-archives:
  enabled:
    - year
    - month
    - day
    - categories
  layout: archive
  permalinks:
    category: '/articles/:name/'

feed:
  path: atom.xml

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
